### ISSUE TITLE
Fix to groff 1.23 leaving left and right indented .item macro on new separate lines

### ISSUE THREAD

**Issue by unclereeemus** [wlcsm/resume#1]
Hi Will, this is a really elegant resume format, thanks a lot for sharing! I just wanted to leave this here to save people who don't know much about groff (like myself) some time and frustration due to the new groff update breaking some things

Basically groff 1.23 breaks the item macro so now instead of 

```
|{Company}              {Duration}|
|{Job title}            {Location}|
```
You get

```
|{Company}              
|{Job title}  
{Duration}|         
{Location}|



```

To fix that, change lines 40-52 in resume.tmac from

```
.de item
.nf
.mk
.DS L
\fB\s(12\\$1\fR
\m[grey]\fI\s(12\\$2\m[]
.DE
.rt
.DS R
\fB\s(11\\$3
\m[grey]\fI\s(12\\$4\m[]
.DE
.sp -0.5
```

To

```
.de item
.nf
.mk
\# .DS L
\fB\s(12\\$1\fR
\m[grey]\fI\s(12\\$2\m[]
\# .DE
.rt
.DS R
\fB\s(11\\$3
\m[grey]\fI\s(12\\$4\m[]
.sp -0.7
.DE
```

**Comment by wlcsm** [comment]
Hey @unclereeemus, thanks for your appreciation!

I've always found groff's `.mk` and `.rt` a bit temperamental. Looks like they no longer work when a display block is put inside them.

I've created a pull request to fix this issue based on your change. Though I've swapped around the spacing to ensure the left and right aligned text is vertically aligned. Please check it all looks good on your resume.

Before merging, I'd also like to confirm it doesn't break resume's built in groff 1.22.
I'd appreciate any help on this, since I can't find an easy way to downgrade on Mac.

**Comment by unclereeemus** [comment]
Hey that works much better than my solution; i didn't even notice the right side wasn't vertically aligned 🤦 . As for trying it out on groff 1.22, I am not able to downgrade easily either, so can't help there, sorry.

Thanks for getting back. Feel free to close the issue when you see fit.

**Comment by wlcsm** [comment]
I've merged the PR
